name: Scraper Workflow

on:
  schedule:
    - cron: '0 0 * * *' # প্রতিদিন স্বয়ংক্রিয়ভাবে চলবে
  workflow_dispatch: # হাতে চেপে যেকোনো সময় চালু করার জন্য

jobs:
  run-scraper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Scraper
        env:
          SERPER_API_KEY: ${{ secrets.SERPER_API_KEY }}
        run: |
          echo "Automated search is running using Serper API..."
